version: '3.9'
services:
  db:
    image: redis
    restart: always
    environment:
      - REDIS_ARGS=--requirepass $REDIS_PASSWORD
      - REDIS_PASSWORD=test
      - REDIS_DATABASE=1
    command: redis-server --requirepass $REDIS_PASSWORD
  urlapp:
    image: urlapp:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    environment:
      - REDIS_HOST=db
      - REDIS_DATABASE=1
      - REDIS_PASSWORD=test
      - REDIS_PORT=6379    
    depends_on:
      - db
