// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"url-shortner/internal/app/handler"
	"url-shortner/internal/app/server"
	"url-shortner/internal/app/service"
	"url-shortner/internal/app/utils"
	"url-shortner/internal/config"
	"url-shortner/pkg/redis"
)

// Injectors from wire.go:

func InitializeServer() (server.Server, func(), error) {
	configuration := config.NewConfig()
	utility := utils.NewUtilityService()
	redisService := redis.NewRedisClient(configuration)
	serviceService := service.NewURLShortnerService(configuration, utility, redisService)
	baseHandler := handler.NewBaseHandler(configuration, serviceService)
	engine := server.NewAppRoutes(configuration, baseHandler)
	serverServer := server.NewURLShortenerServer(configuration, engine)
	return serverServer, func() {
	}, nil
}
